import 'package:cokc/app/stat/enum/stat-code.enum.dart';
import 'package:cokc/database/box/stat-config.box.dart';
import 'package:cokc/database/box/stat-progression-config.box.dart';
import 'package:cokc/database/constant/table-collection.constant.dart';
import 'package:cokc/database/seed/base.seed.dart';
import 'package:hive_flutter/hive_flutter.dart';

class StatConfigSeed extends BaseSeed {
  @override
  Future seed() async {
    if (Hive.box<StatConfig>(TableCollection.statConfig).length <= 0) {
      await Hive.box<StatConfig>(TableCollection.statConfig).addAll([
        StatConfig(
          code: StatCode.maximumHp.index,
          minimumPoint: 1,
          maximumPoint: 25,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
            StatProgressionConfig(point: 6, value: 6),
            StatProgressionConfig(point: 7, value: 7),
            StatProgressionConfig(point: 8, value: 8),
            StatProgressionConfig(point: 9, value: 9),
            StatProgressionConfig(point: 10, value: 10),
            StatProgressionConfig(point: 11, value: 11),
            StatProgressionConfig(point: 12, value: 12),
            StatProgressionConfig(point: 13, value: 13),
            StatProgressionConfig(point: 14, value: 14),
            StatProgressionConfig(point: 15, value: 15),
            StatProgressionConfig(point: 16, value: 16),
            StatProgressionConfig(point: 17, value: 17),
            StatProgressionConfig(point: 18, value: 18),
            StatProgressionConfig(point: 19, value: 19),
            StatProgressionConfig(point: 20, value: 20),
            StatProgressionConfig(point: 21, value: 21),
            StatProgressionConfig(point: 22, value: 22),
            StatProgressionConfig(point: 23, value: 23),
            StatProgressionConfig(point: 24, value: 24),
            StatProgressionConfig(point: 25, value: 25),
          ],
        ),
        StatConfig(
          code: StatCode.currentHp.index,
          minimumPoint: 0,
          maximumPoint: 25,
          progressionConfigList: [
            StatProgressionConfig(point: 0, value: 0),
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
            StatProgressionConfig(point: 6, value: 6),
            StatProgressionConfig(point: 7, value: 7),
            StatProgressionConfig(point: 8, value: 8),
            StatProgressionConfig(point: 9, value: 9),
            StatProgressionConfig(point: 10, value: 10),
            StatProgressionConfig(point: 11, value: 11),
            StatProgressionConfig(point: 12, value: 12),
            StatProgressionConfig(point: 13, value: 13),
            StatProgressionConfig(point: 14, value: 14),
            StatProgressionConfig(point: 15, value: 15),
            StatProgressionConfig(point: 16, value: 16),
            StatProgressionConfig(point: 17, value: 17),
            StatProgressionConfig(point: 18, value: 18),
            StatProgressionConfig(point: 19, value: 19),
            StatProgressionConfig(point: 20, value: 20),
            StatProgressionConfig(point: 21, value: 21),
            StatProgressionConfig(point: 22, value: 22),
            StatProgressionConfig(point: 23, value: 23),
            StatProgressionConfig(point: 24, value: 24),
            StatProgressionConfig(point: 25, value: 25),
          ],
        ),
        StatConfig(
          code: StatCode.attack.index,
          minimumPoint: 1,
          maximumPoint: 10,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
            StatProgressionConfig(point: 6, value: 6),
            StatProgressionConfig(point: 7, value: 7),
            StatProgressionConfig(point: 8, value: 8),
            StatProgressionConfig(point: 9, value: 9),
            StatProgressionConfig(point: 10, value: 10),
          ],
        ),
        StatConfig(
          code: StatCode.heal.index,
          minimumPoint: 1,
          maximumPoint: 10,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
            StatProgressionConfig(point: 6, value: 6),
            StatProgressionConfig(point: 7, value: 7),
            StatProgressionConfig(point: 8, value: 8),
            StatProgressionConfig(point: 9, value: 9),
            StatProgressionConfig(point: 10, value: 10),
          ],
        ),
        StatConfig(
          code: StatCode.range.index,
          minimumPoint: 1,
          maximumPoint: 10,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 1),
            StatProgressionConfig(point: 3, value: 2),
            StatProgressionConfig(point: 4, value: 2),
            StatProgressionConfig(point: 5, value: 3),
            StatProgressionConfig(point: 6, value: 3),
            StatProgressionConfig(point: 7, value: 4),
            StatProgressionConfig(point: 8, value: 4),
            StatProgressionConfig(point: 9, value: 4),
            StatProgressionConfig(point: 10, value: 5),
          ],
        ),
        StatConfig(
          code: StatCode.playerMove.index,
          minimumPoint: 1,
          maximumPoint: 10,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 1),
            StatProgressionConfig(point: 3, value: 2),
            StatProgressionConfig(point: 4, value: 2),
            StatProgressionConfig(point: 5, value: 3),
            StatProgressionConfig(point: 6, value: 3),
            StatProgressionConfig(point: 7, value: 4),
            StatProgressionConfig(point: 8, value: 4),
            StatProgressionConfig(point: 9, value: 4),
            StatProgressionConfig(point: 10, value: 5),
          ],
        ),
        StatConfig(
          code: StatCode.luck.index,
          minimumPoint: 0,
          maximumPoint: 10,
          progressionConfigList: [
            StatProgressionConfig(point: 0, value: 0),
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 1),
            StatProgressionConfig(point: 3, value: 2),
            StatProgressionConfig(point: 4, value: 2),
            StatProgressionConfig(point: 5, value: 3),
            StatProgressionConfig(point: 6, value: 3),
            StatProgressionConfig(point: 7, value: 4),
            StatProgressionConfig(point: 8, value: 4),
            StatProgressionConfig(point: 9, value: 4),
            StatProgressionConfig(point: 10, value: 5),
          ],
        ),
        StatConfig(
          code: StatCode.workerMove.index,
          minimumPoint: 1,
          maximumPoint: 5,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
          ],
        ),
        StatConfig(
          code: StatCode.gather.index,
          minimumPoint: 1,
          maximumPoint: 5,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
          ],
        ),
        StatConfig(
          code: StatCode.scavenge.index,
          minimumPoint: 1,
          maximumPoint: 5,
          progressionConfigList: [
            StatProgressionConfig(point: 1, value: 1),
            StatProgressionConfig(point: 2, value: 2),
            StatProgressionConfig(point: 3, value: 3),
            StatProgressionConfig(point: 4, value: 4),
            StatProgressionConfig(point: 5, value: 5),
          ],
        ),
      ]);
    }
  }
}
